<?php

namespace Acme\TestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * phoneTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class phoneTypesRepository extends EntityRepository
{
}